data_dir: /grogu/user/pmorgado/projects/streamssl/experiments/simsiam/
resume: True
world_size: 1
rank: 0
workers: 64
multiprocessing_distributed: True
distributed: True
dist_backend: 'nccl'
dist_url: 'tcp://224.66.41.62:23456'
node: 'localhost'
port: 21992
seed: 0
gpu: ''
ngpu: 8
mem_gb: 128
slurm: False
slurm_partition: special
slurm_timeout: 360
print_freq: ${logging.print_freq}
evaluate: False
nodelist: ""
exclude_nodes: ""
