epochs: 1
start_epoch: 0
start_batch_idx: 0
batch_size: 256
lr: 0.1
fix_pred_lr: True
momentum: 0.9
weight_decay: 0.0001
lr_schedule:
  type: "cos"    # constant, cos, triangle
  period: 3000
  max_lr: 0.003
  exit_decay: 0.
